apiVersion: v1
kind: Namespace
metadata:
  name: probler-box
  labels:
    name: probler-box

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: probler-box
  name: probler-box
  labels:
    app: probler-box
spec:
  selector:
    matchLabels:
      app: probler-box
  template:
    metadata:
      labels:
        app: probler-box
    spec:
      containers:
        - name: probler-box
          image: saichler/probler-inv-box:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP