apiVersion: v1
kind: Namespace
metadata:
  name: probler-parser
  labels:
    name: probler-parser

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: probler-parser
  name: probler-parser
  labels:
    app: probler-parser
spec:
  replicas: 12
  selector:
    matchLabels:
      app: probler-parser
  template:
    metadata:
      labels:
        app: probler-parser
    spec:
      containers:
        - name: probler-parser
          image: saichler/probler-parser:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
