// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `vcluster.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

///  vCluster (SA 17)
// @@protoc_insertion_point(message:types.K8SVCluster)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct K8SVCluster {
    // message fields
    // @@protoc_insertion_point(field:types.K8SVCluster.namespace)
    pub namespace: ::std::string::String,
    // @@protoc_insertion_point(field:types.K8SVCluster.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:types.K8SVCluster.status)
    pub status: ::std::string::String,
    // @@protoc_insertion_point(field:types.K8SVCluster.k8s_version)
    pub k8s_version: ::std::string::String,
    // @@protoc_insertion_point(field:types.K8SVCluster.distro)
    pub distro: ::std::string::String,
    // @@protoc_insertion_point(field:types.K8SVCluster.connected)
    pub connected: ::std::string::String,
    // @@protoc_insertion_point(field:types.K8SVCluster.synced_pods)
    pub synced_pods: i32,
    // @@protoc_insertion_point(field:types.K8SVCluster.synced_services)
    pub synced_services: i32,
    // @@protoc_insertion_point(field:types.K8SVCluster.synced_ingresses)
    pub synced_ingresses: i32,
    // @@protoc_insertion_point(field:types.K8SVCluster.age)
    pub age: ::std::string::String,
    // @@protoc_insertion_point(field:types.K8SVCluster.cluster_name)
    pub cluster_name: ::std::string::String,
    // @@protoc_insertion_point(field:types.K8SVCluster.key)
    pub key: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:types.K8SVCluster.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a K8SVCluster {
    fn default() -> &'a K8SVCluster {
        <K8SVCluster as ::protobuf::Message>::default_instance()
    }
}

impl K8SVCluster {
    pub fn new() -> K8SVCluster {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(12);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "namespace",
            |m: &K8SVCluster| { &m.namespace },
            |m: &mut K8SVCluster| { &mut m.namespace },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &K8SVCluster| { &m.name },
            |m: &mut K8SVCluster| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "status",
            |m: &K8SVCluster| { &m.status },
            |m: &mut K8SVCluster| { &mut m.status },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "k8s_version",
            |m: &K8SVCluster| { &m.k8s_version },
            |m: &mut K8SVCluster| { &mut m.k8s_version },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "distro",
            |m: &K8SVCluster| { &m.distro },
            |m: &mut K8SVCluster| { &mut m.distro },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "connected",
            |m: &K8SVCluster| { &m.connected },
            |m: &mut K8SVCluster| { &mut m.connected },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "synced_pods",
            |m: &K8SVCluster| { &m.synced_pods },
            |m: &mut K8SVCluster| { &mut m.synced_pods },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "synced_services",
            |m: &K8SVCluster| { &m.synced_services },
            |m: &mut K8SVCluster| { &mut m.synced_services },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "synced_ingresses",
            |m: &K8SVCluster| { &m.synced_ingresses },
            |m: &mut K8SVCluster| { &mut m.synced_ingresses },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "age",
            |m: &K8SVCluster| { &m.age },
            |m: &mut K8SVCluster| { &mut m.age },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "cluster_name",
            |m: &K8SVCluster| { &m.cluster_name },
            |m: &mut K8SVCluster| { &mut m.cluster_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "key",
            |m: &K8SVCluster| { &m.key },
            |m: &mut K8SVCluster| { &mut m.key },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<K8SVCluster>(
            "K8SVCluster",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for K8SVCluster {
    const NAME: &'static str = "K8SVCluster";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.namespace = is.read_string()?;
                },
                18 => {
                    self.name = is.read_string()?;
                },
                26 => {
                    self.status = is.read_string()?;
                },
                34 => {
                    self.k8s_version = is.read_string()?;
                },
                42 => {
                    self.distro = is.read_string()?;
                },
                50 => {
                    self.connected = is.read_string()?;
                },
                56 => {
                    self.synced_pods = is.read_int32()?;
                },
                64 => {
                    self.synced_services = is.read_int32()?;
                },
                72 => {
                    self.synced_ingresses = is.read_int32()?;
                },
                82 => {
                    self.age = is.read_string()?;
                },
                802 => {
                    self.cluster_name = is.read_string()?;
                },
                810 => {
                    self.key = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.namespace.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.namespace);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if !self.status.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.status);
        }
        if !self.k8s_version.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.k8s_version);
        }
        if !self.distro.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.distro);
        }
        if !self.connected.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.connected);
        }
        if self.synced_pods != 0 {
            my_size += ::protobuf::rt::int32_size(7, self.synced_pods);
        }
        if self.synced_services != 0 {
            my_size += ::protobuf::rt::int32_size(8, self.synced_services);
        }
        if self.synced_ingresses != 0 {
            my_size += ::protobuf::rt::int32_size(9, self.synced_ingresses);
        }
        if !self.age.is_empty() {
            my_size += ::protobuf::rt::string_size(10, &self.age);
        }
        if !self.cluster_name.is_empty() {
            my_size += ::protobuf::rt::string_size(100, &self.cluster_name);
        }
        if !self.key.is_empty() {
            my_size += ::protobuf::rt::string_size(101, &self.key);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.namespace.is_empty() {
            os.write_string(1, &self.namespace)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if !self.status.is_empty() {
            os.write_string(3, &self.status)?;
        }
        if !self.k8s_version.is_empty() {
            os.write_string(4, &self.k8s_version)?;
        }
        if !self.distro.is_empty() {
            os.write_string(5, &self.distro)?;
        }
        if !self.connected.is_empty() {
            os.write_string(6, &self.connected)?;
        }
        if self.synced_pods != 0 {
            os.write_int32(7, self.synced_pods)?;
        }
        if self.synced_services != 0 {
            os.write_int32(8, self.synced_services)?;
        }
        if self.synced_ingresses != 0 {
            os.write_int32(9, self.synced_ingresses)?;
        }
        if !self.age.is_empty() {
            os.write_string(10, &self.age)?;
        }
        if !self.cluster_name.is_empty() {
            os.write_string(100, &self.cluster_name)?;
        }
        if !self.key.is_empty() {
            os.write_string(101, &self.key)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> K8SVCluster {
        K8SVCluster::new()
    }

    fn clear(&mut self) {
        self.namespace.clear();
        self.name.clear();
        self.status.clear();
        self.k8s_version.clear();
        self.distro.clear();
        self.connected.clear();
        self.synced_pods = 0;
        self.synced_services = 0;
        self.synced_ingresses = 0;
        self.age.clear();
        self.cluster_name.clear();
        self.key.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static K8SVCluster {
        static instance: K8SVCluster = K8SVCluster {
            namespace: ::std::string::String::new(),
            name: ::std::string::String::new(),
            status: ::std::string::String::new(),
            k8s_version: ::std::string::String::new(),
            distro: ::std::string::String::new(),
            connected: ::std::string::String::new(),
            synced_pods: 0,
            synced_services: 0,
            synced_ingresses: 0,
            age: ::std::string::String::new(),
            cluster_name: ::std::string::String::new(),
            key: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for K8SVCluster {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("K8SVCluster").unwrap()).clone()
    }
}

impl ::std::fmt::Display for K8SVCluster {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for K8SVCluster {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:types.K8SVClusterList)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct K8SVClusterList {
    // message fields
    // @@protoc_insertion_point(field:types.K8SVClusterList.list)
    pub list: ::std::vec::Vec<K8SVCluster>,
    // @@protoc_insertion_point(field:types.K8SVClusterList.metadata)
    pub metadata: ::protobuf::MessageField<super::api::L8MetaData>,
    // special fields
    // @@protoc_insertion_point(special_field:types.K8SVClusterList.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a K8SVClusterList {
    fn default() -> &'a K8SVClusterList {
        <K8SVClusterList as ::protobuf::Message>::default_instance()
    }
}

impl K8SVClusterList {
    pub fn new() -> K8SVClusterList {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "list",
            |m: &K8SVClusterList| { &m.list },
            |m: &mut K8SVClusterList| { &mut m.list },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::api::L8MetaData>(
            "metadata",
            |m: &K8SVClusterList| { &m.metadata },
            |m: &mut K8SVClusterList| { &mut m.metadata },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<K8SVClusterList>(
            "K8SVClusterList",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for K8SVClusterList {
    const NAME: &'static str = "K8SVClusterList";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.list.push(is.read_message()?);
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.metadata)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.metadata.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.list {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        if let Some(v) = self.metadata.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> K8SVClusterList {
        K8SVClusterList::new()
    }

    fn clear(&mut self) {
        self.list.clear();
        self.metadata.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static K8SVClusterList {
        static instance: K8SVClusterList = K8SVClusterList {
            list: ::std::vec::Vec::new(),
            metadata: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for K8SVClusterList {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("K8SVClusterList").unwrap()).clone()
    }
}

impl ::std::fmt::Display for K8SVClusterList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for K8SVClusterList {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0evcluster.proto\x12\x05types\x1a\tapi.proto\"\xea\x02\n\x0bK8SVClus\
    ter\x12\x1c\n\tnamespace\x18\x01\x20\x01(\tR\tnamespace\x12\x12\n\x04nam\
    e\x18\x02\x20\x01(\tR\x04name\x12\x16\n\x06status\x18\x03\x20\x01(\tR\
    \x06status\x12\x1f\n\x0bk8s_version\x18\x04\x20\x01(\tR\nk8sVersion\x12\
    \x16\n\x06distro\x18\x05\x20\x01(\tR\x06distro\x12\x1c\n\tconnected\x18\
    \x06\x20\x01(\tR\tconnected\x12\x1f\n\x0bsynced_pods\x18\x07\x20\x01(\
    \x05R\nsyncedPods\x12'\n\x0fsynced_services\x18\x08\x20\x01(\x05R\x0esyn\
    cedServices\x12)\n\x10synced_ingresses\x18\t\x20\x01(\x05R\x0fsyncedIngr\
    esses\x12\x10\n\x03age\x18\n\x20\x01(\tR\x03age\x12!\n\x0ccluster_name\
    \x18d\x20\x01(\tR\x0bclusterName\x12\x10\n\x03key\x18e\x20\x01(\tR\x03ke\
    y\"h\n\x0fK8SVClusterList\x12&\n\x04list\x18\x01\x20\x03(\x0b2\x12.types\
    .K8SVClusterR\x04list\x12-\n\x08metadata\x18\x02\x20\x01(\x0b2\x11.l8api\
    .L8MetaDataR\x08metadataB!\n\rcom.k8s.typesB\x05TypesP\x01Z\x07./typesJ\
    \xda\x0b\n\x06\x12\x04\x0f\0+\x01\n\x92\x04\n\x01\x0c\x12\x03\x0f\0\x122\
    \x87\x04\n\x20\xc2\xa9\x202025\x20Sharon\x20Aicler\x20(saichler@gmail.co\
    m)\n\n\x20Layer\x208\x20Ecosystem\x20is\x20licensed\x20under\x20the\x20A\
    pache\x20License,\x20Version\x202.0.\n\x20You\x20may\x20obtain\x20a\x20c\
    opy\x20of\x20the\x20License\x20at:\n\n\x20\x20\x20\x20\x20http://www.apa\
    che.org/licenses/LICENSE-2.0\n\n\x20Unless\x20required\x20by\x20applicab\
    le\x20law\x20or\x20agreed\x20to\x20in\x20writing,\x20software\n\x20distr\
    ibuted\x20under\x20the\x20License\x20is\x20distributed\x20on\x20an\x20\"\
    AS\x20IS\"\x20BASIS,\n\x20WITHOUT\x20WARRANTIES\x20OR\x20CONDITIONS\x20O\
    F\x20ANY\x20KIND,\x20either\x20express\x20or\x20implied.\n\x20See\x20the\
    \x20License\x20for\x20the\x20specific\x20language\x20governing\x20permis\
    sions\x20and\n\x20limitations\x20under\x20the\x20License.\n\n\x08\n\x01\
    \x02\x12\x03\x11\0\x0e\n\x08\n\x01\x08\x12\x03\x13\0\"\n\t\n\x02\x08\n\
    \x12\x03\x13\0\"\n\x08\n\x01\x08\x12\x03\x14\0&\n\t\n\x02\x08\x08\x12\
    \x03\x14\0&\n\x08\n\x01\x08\x12\x03\x15\0&\n\t\n\x02\x08\x01\x12\x03\x15\
    \0&\n\x08\n\x01\x08\x12\x03\x16\0\x1e\n\t\n\x02\x08\x0b\x12\x03\x16\0\
    \x1e\n\t\n\x02\x03\0\x12\x03\x17\0\x13\n\x1e\n\x02\x04\0\x12\x04\x1a\0'\
    \x01\x1a\x12\x20vCluster\x20(SA\x2017)\n\n\n\n\x03\x04\0\x01\x12\x03\x1a\
    \x08\x13\n\x0b\n\x04\x04\0\x02\0\x12\x03\x1b\x02\x17\n\x0c\n\x05\x04\0\
    \x02\0\x05\x12\x03\x1b\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x1b\t\
    \x12\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x1b\x15\x16\n\x0b\n\x04\x04\0\
    \x02\x01\x12\x03\x1c\x02\x12\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x1c\
    \x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x1c\t\r\n\x0c\n\x05\x04\0\
    \x02\x01\x03\x12\x03\x1c\x10\x11\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x1d\
    \x02\x14\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x1d\x02\x08\n\x0c\n\x05\
    \x04\0\x02\x02\x01\x12\x03\x1d\t\x0f\n\x0c\n\x05\x04\0\x02\x02\x03\x12\
    \x03\x1d\x12\x13\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x1e\x02\x19\n\x0c\n\
    \x05\x04\0\x02\x03\x05\x12\x03\x1e\x02\x08\n\x0c\n\x05\x04\0\x02\x03\x01\
    \x12\x03\x1e\t\x14\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x1e\x17\x18\n\
    \x0b\n\x04\x04\0\x02\x04\x12\x03\x1f\x02\x14\n\x0c\n\x05\x04\0\x02\x04\
    \x05\x12\x03\x1f\x02\x08\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\x1f\t\x0f\
    \n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\x1f\x12\x13\n\x0b\n\x04\x04\0\x02\
    \x05\x12\x03\x20\x02\x17\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\x20\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03\x20\t\x12\n\x0c\n\x05\x04\0\
    \x02\x05\x03\x12\x03\x20\x15\x16\n\x0b\n\x04\x04\0\x02\x06\x12\x03!\x02\
    \x18\n\x0c\n\x05\x04\0\x02\x06\x05\x12\x03!\x02\x07\n\x0c\n\x05\x04\0\
    \x02\x06\x01\x12\x03!\x08\x13\n\x0c\n\x05\x04\0\x02\x06\x03\x12\x03!\x16\
    \x17\n\x0b\n\x04\x04\0\x02\x07\x12\x03\"\x02\x1c\n\x0c\n\x05\x04\0\x02\
    \x07\x05\x12\x03\"\x02\x07\n\x0c\n\x05\x04\0\x02\x07\x01\x12\x03\"\x08\
    \x17\n\x0c\n\x05\x04\0\x02\x07\x03\x12\x03\"\x1a\x1b\n\x0b\n\x04\x04\0\
    \x02\x08\x12\x03#\x02\x1d\n\x0c\n\x05\x04\0\x02\x08\x05\x12\x03#\x02\x07\
    \n\x0c\n\x05\x04\0\x02\x08\x01\x12\x03#\x08\x18\n\x0c\n\x05\x04\0\x02\
    \x08\x03\x12\x03#\x1b\x1c\n\x0b\n\x04\x04\0\x02\t\x12\x03$\x02\x12\n\x0c\
    \n\x05\x04\0\x02\t\x05\x12\x03$\x02\x08\n\x0c\n\x05\x04\0\x02\t\x01\x12\
    \x03$\t\x0c\n\x0c\n\x05\x04\0\x02\t\x03\x12\x03$\x0f\x11\n\x0b\n\x04\x04\
    \0\x02\n\x12\x03%\x02\x1c\n\x0c\n\x05\x04\0\x02\n\x05\x12\x03%\x02\x08\n\
    \x0c\n\x05\x04\0\x02\n\x01\x12\x03%\t\x15\n\x0c\n\x05\x04\0\x02\n\x03\
    \x12\x03%\x18\x1b\n\x0b\n\x04\x04\0\x02\x0b\x12\x03&\x02\x13\n\x0c\n\x05\
    \x04\0\x02\x0b\x05\x12\x03&\x02\x08\n\x0c\n\x05\x04\0\x02\x0b\x01\x12\
    \x03&\t\x0c\n\x0c\n\x05\x04\0\x02\x0b\x03\x12\x03&\x0f\x12\n\n\n\x02\x04\
    \x01\x12\x04(\0+\x01\n\n\n\x03\x04\x01\x01\x12\x03(\x08\x17\n\x0b\n\x04\
    \x04\x01\x02\0\x12\x03)\x02\x20\n\x0c\n\x05\x04\x01\x02\0\x04\x12\x03)\
    \x02\n\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03)\x0b\x16\n\x0c\n\x05\x04\
    \x01\x02\0\x01\x12\x03)\x17\x1b\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03)\
    \x1e\x1f\n\x0b\n\x04\x04\x01\x02\x01\x12\x03*\x02\x20\n\x0c\n\x05\x04\
    \x01\x02\x01\x06\x12\x03*\x02\x12\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\
    \x03*\x13\x1b\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03*\x1e\x1fb\x06proto\
    3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::api::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(K8SVCluster::generated_message_descriptor_data());
            messages.push(K8SVClusterList::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
