//
// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: istio.proto

package types

import (
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Istio Service Mesh (SA 18)
type IstioVirtualService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gateways    string `protobuf:"bytes,3,opt,name=gateways,proto3" json:"gateways,omitempty"`
	Hosts       string `protobuf:"bytes,4,opt,name=hosts,proto3" json:"hosts,omitempty"`
	Age         string `protobuf:"bytes,5,opt,name=age,proto3" json:"age,omitempty"`
	ClusterName string `protobuf:"bytes,100,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Key         string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *IstioVirtualService) Reset() {
	*x = IstioVirtualService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioVirtualService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioVirtualService) ProtoMessage() {}

func (x *IstioVirtualService) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioVirtualService.ProtoReflect.Descriptor instead.
func (*IstioVirtualService) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{0}
}

func (x *IstioVirtualService) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IstioVirtualService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IstioVirtualService) GetGateways() string {
	if x != nil {
		return x.Gateways
	}
	return ""
}

func (x *IstioVirtualService) GetHosts() string {
	if x != nil {
		return x.Hosts
	}
	return ""
}

func (x *IstioVirtualService) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *IstioVirtualService) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *IstioVirtualService) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IstioVirtualServiceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*IstioVirtualService `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *IstioVirtualServiceList) Reset() {
	*x = IstioVirtualServiceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioVirtualServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioVirtualServiceList) ProtoMessage() {}

func (x *IstioVirtualServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioVirtualServiceList.ProtoReflect.Descriptor instead.
func (*IstioVirtualServiceList) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{1}
}

func (x *IstioVirtualServiceList) GetList() []*IstioVirtualService {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *IstioVirtualServiceList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IstioDestinationRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host        string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Age         string `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	ClusterName string `protobuf:"bytes,100,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Key         string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *IstioDestinationRule) Reset() {
	*x = IstioDestinationRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioDestinationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioDestinationRule) ProtoMessage() {}

func (x *IstioDestinationRule) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioDestinationRule.ProtoReflect.Descriptor instead.
func (*IstioDestinationRule) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{2}
}

func (x *IstioDestinationRule) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IstioDestinationRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IstioDestinationRule) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *IstioDestinationRule) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *IstioDestinationRule) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *IstioDestinationRule) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IstioDestinationRuleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*IstioDestinationRule `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *IstioDestinationRuleList) Reset() {
	*x = IstioDestinationRuleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioDestinationRuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioDestinationRuleList) ProtoMessage() {}

func (x *IstioDestinationRuleList) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioDestinationRuleList.ProtoReflect.Descriptor instead.
func (*IstioDestinationRuleList) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{3}
}

func (x *IstioDestinationRuleList) GetList() []*IstioDestinationRule {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *IstioDestinationRuleList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IstioGateway struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Servers     string `protobuf:"bytes,3,opt,name=servers,proto3" json:"servers,omitempty"`
	Selector    string `protobuf:"bytes,4,opt,name=selector,proto3" json:"selector,omitempty"`
	Age         string `protobuf:"bytes,5,opt,name=age,proto3" json:"age,omitempty"`
	ClusterName string `protobuf:"bytes,100,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Key         string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *IstioGateway) Reset() {
	*x = IstioGateway{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioGateway) ProtoMessage() {}

func (x *IstioGateway) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioGateway.ProtoReflect.Descriptor instead.
func (*IstioGateway) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{4}
}

func (x *IstioGateway) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IstioGateway) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IstioGateway) GetServers() string {
	if x != nil {
		return x.Servers
	}
	return ""
}

func (x *IstioGateway) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *IstioGateway) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *IstioGateway) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *IstioGateway) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IstioGatewayList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*IstioGateway   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *IstioGatewayList) Reset() {
	*x = IstioGatewayList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioGatewayList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioGatewayList) ProtoMessage() {}

func (x *IstioGatewayList) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioGatewayList.ProtoReflect.Descriptor instead.
func (*IstioGatewayList) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{5}
}

func (x *IstioGatewayList) GetList() []*IstioGateway {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *IstioGatewayList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IstioServiceEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hosts       string `protobuf:"bytes,3,opt,name=hosts,proto3" json:"hosts,omitempty"`
	Location    string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Resolution  string `protobuf:"bytes,5,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Ports       string `protobuf:"bytes,6,opt,name=ports,proto3" json:"ports,omitempty"`
	Age         string `protobuf:"bytes,7,opt,name=age,proto3" json:"age,omitempty"`
	ClusterName string `protobuf:"bytes,100,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Key         string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *IstioServiceEntry) Reset() {
	*x = IstioServiceEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioServiceEntry) ProtoMessage() {}

func (x *IstioServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioServiceEntry.ProtoReflect.Descriptor instead.
func (*IstioServiceEntry) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{6}
}

func (x *IstioServiceEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IstioServiceEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IstioServiceEntry) GetHosts() string {
	if x != nil {
		return x.Hosts
	}
	return ""
}

func (x *IstioServiceEntry) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *IstioServiceEntry) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *IstioServiceEntry) GetPorts() string {
	if x != nil {
		return x.Ports
	}
	return ""
}

func (x *IstioServiceEntry) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *IstioServiceEntry) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *IstioServiceEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IstioServiceEntryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*IstioServiceEntry `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *IstioServiceEntryList) Reset() {
	*x = IstioServiceEntryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioServiceEntryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioServiceEntryList) ProtoMessage() {}

func (x *IstioServiceEntryList) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioServiceEntryList.ProtoReflect.Descriptor instead.
func (*IstioServiceEntryList) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{7}
}

func (x *IstioServiceEntryList) GetList() []*IstioServiceEntry {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *IstioServiceEntryList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IstioPeerAuthentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode        string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Age         string `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	ClusterName string `protobuf:"bytes,100,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Key         string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *IstioPeerAuthentication) Reset() {
	*x = IstioPeerAuthentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioPeerAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioPeerAuthentication) ProtoMessage() {}

func (x *IstioPeerAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioPeerAuthentication.ProtoReflect.Descriptor instead.
func (*IstioPeerAuthentication) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{8}
}

func (x *IstioPeerAuthentication) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IstioPeerAuthentication) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IstioPeerAuthentication) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *IstioPeerAuthentication) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *IstioPeerAuthentication) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *IstioPeerAuthentication) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IstioPeerAuthenticationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*IstioPeerAuthentication `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *IstioPeerAuthenticationList) Reset() {
	*x = IstioPeerAuthenticationList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioPeerAuthenticationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioPeerAuthenticationList) ProtoMessage() {}

func (x *IstioPeerAuthenticationList) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioPeerAuthenticationList.ProtoReflect.Descriptor instead.
func (*IstioPeerAuthenticationList) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{9}
}

func (x *IstioPeerAuthenticationList) GetList() []*IstioPeerAuthentication {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *IstioPeerAuthenticationList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IstioAuthorizationPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Action      string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Age         string `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	ClusterName string `protobuf:"bytes,100,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Key         string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *IstioAuthorizationPolicy) Reset() {
	*x = IstioAuthorizationPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioAuthorizationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioAuthorizationPolicy) ProtoMessage() {}

func (x *IstioAuthorizationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioAuthorizationPolicy.ProtoReflect.Descriptor instead.
func (*IstioAuthorizationPolicy) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{10}
}

func (x *IstioAuthorizationPolicy) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IstioAuthorizationPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IstioAuthorizationPolicy) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *IstioAuthorizationPolicy) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *IstioAuthorizationPolicy) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *IstioAuthorizationPolicy) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IstioAuthorizationPolicyList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*IstioAuthorizationPolicy `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData           `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *IstioAuthorizationPolicyList) Reset() {
	*x = IstioAuthorizationPolicyList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioAuthorizationPolicyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioAuthorizationPolicyList) ProtoMessage() {}

func (x *IstioAuthorizationPolicyList) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioAuthorizationPolicyList.ProtoReflect.Descriptor instead.
func (*IstioAuthorizationPolicyList) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{11}
}

func (x *IstioAuthorizationPolicyList) GetList() []*IstioAuthorizationPolicy {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *IstioAuthorizationPolicyList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IstioSidecar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age         string `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	ClusterName string `protobuf:"bytes,100,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Key         string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *IstioSidecar) Reset() {
	*x = IstioSidecar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioSidecar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioSidecar) ProtoMessage() {}

func (x *IstioSidecar) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioSidecar.ProtoReflect.Descriptor instead.
func (*IstioSidecar) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{12}
}

func (x *IstioSidecar) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IstioSidecar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IstioSidecar) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *IstioSidecar) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *IstioSidecar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IstioSidecarList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*IstioSidecar   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *IstioSidecarList) Reset() {
	*x = IstioSidecarList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioSidecarList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioSidecarList) ProtoMessage() {}

func (x *IstioSidecarList) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioSidecarList.ProtoReflect.Descriptor instead.
func (*IstioSidecarList) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{13}
}

func (x *IstioSidecarList) GetList() []*IstioSidecar {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *IstioSidecarList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IstioEnvoyFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace   string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age         string `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	ClusterName string `protobuf:"bytes,100,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Key         string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *IstioEnvoyFilter) Reset() {
	*x = IstioEnvoyFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioEnvoyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioEnvoyFilter) ProtoMessage() {}

func (x *IstioEnvoyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioEnvoyFilter.ProtoReflect.Descriptor instead.
func (*IstioEnvoyFilter) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{14}
}

func (x *IstioEnvoyFilter) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IstioEnvoyFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IstioEnvoyFilter) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *IstioEnvoyFilter) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *IstioEnvoyFilter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IstioEnvoyFilterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*IstioEnvoyFilter `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *IstioEnvoyFilterList) Reset() {
	*x = IstioEnvoyFilterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_istio_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IstioEnvoyFilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IstioEnvoyFilterList) ProtoMessage() {}

func (x *IstioEnvoyFilterList) ProtoReflect() protoreflect.Message {
	mi := &file_istio_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IstioEnvoyFilterList.ProtoReflect.Descriptor instead.
func (*IstioEnvoyFilterList) Descriptor() ([]byte, []int) {
	return file_istio_proto_rawDescGZIP(), []int{15}
}

func (x *IstioEnvoyFilterList) GetList() []*IstioEnvoyFilter {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *IstioEnvoyFilterList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_istio_proto protoreflect.FileDescriptor

var file_istio_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x73, 0x74, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc0, 0x01, 0x0a, 0x13, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x64, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x78, 0x0a, 0x17, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x56, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa3, 0x01, 0x0a,
	0x14, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x64, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x7a, 0x0a, 0x18, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x44, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xbd,
	0x01, 0x0a, 0x0c, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x6a,
	0x0a, 0x10, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xf4, 0x01, 0x0a, 0x11, 0x49,
	0x73, 0x74, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x64, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x74, 0x0a, 0x15, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa6, 0x01, 0x0a, 0x17, 0x49, 0x73, 0x74, 0x69,
	0x6f, 0x50, 0x65, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x80, 0x01, 0x0a, 0x1b, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x32, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x50, 0x65, 0x65, 0x72,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c,
	0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xab, 0x01, 0x0a, 0x18, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x64, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x82, 0x01, 0x0a, 0x1c, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x33, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x87, 0x01, 0x0a, 0x0c, 0x49, 0x73, 0x74, 0x69, 0x6f,
	0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x6a, 0x0a, 0x10, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x49, 0x73, 0x74, 0x69, 0x6f,
	0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8b, 0x01, 0x0a,
	0x10, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x45, 0x6e, 0x76, 0x6f, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x72, 0x0a, 0x14, 0x49, 0x73,
	0x74, 0x69, 0x6f, 0x45, 0x6e, 0x76, 0x6f, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x49, 0x73, 0x74, 0x69, 0x6f, 0x45, 0x6e,
	0x76, 0x6f, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0x21,
	0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x38, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x42,
	0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x07, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_istio_proto_rawDescOnce sync.Once
	file_istio_proto_rawDescData = file_istio_proto_rawDesc
)

func file_istio_proto_rawDescGZIP() []byte {
	file_istio_proto_rawDescOnce.Do(func() {
		file_istio_proto_rawDescData = protoimpl.X.CompressGZIP(file_istio_proto_rawDescData)
	})
	return file_istio_proto_rawDescData
}

var file_istio_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_istio_proto_goTypes = []interface{}{
	(*IstioVirtualService)(nil),          // 0: types.IstioVirtualService
	(*IstioVirtualServiceList)(nil),      // 1: types.IstioVirtualServiceList
	(*IstioDestinationRule)(nil),         // 2: types.IstioDestinationRule
	(*IstioDestinationRuleList)(nil),     // 3: types.IstioDestinationRuleList
	(*IstioGateway)(nil),                 // 4: types.IstioGateway
	(*IstioGatewayList)(nil),             // 5: types.IstioGatewayList
	(*IstioServiceEntry)(nil),            // 6: types.IstioServiceEntry
	(*IstioServiceEntryList)(nil),        // 7: types.IstioServiceEntryList
	(*IstioPeerAuthentication)(nil),      // 8: types.IstioPeerAuthentication
	(*IstioPeerAuthenticationList)(nil),  // 9: types.IstioPeerAuthenticationList
	(*IstioAuthorizationPolicy)(nil),     // 10: types.IstioAuthorizationPolicy
	(*IstioAuthorizationPolicyList)(nil), // 11: types.IstioAuthorizationPolicyList
	(*IstioSidecar)(nil),                 // 12: types.IstioSidecar
	(*IstioSidecarList)(nil),             // 13: types.IstioSidecarList
	(*IstioEnvoyFilter)(nil),             // 14: types.IstioEnvoyFilter
	(*IstioEnvoyFilterList)(nil),         // 15: types.IstioEnvoyFilterList
	(*l8api.L8MetaData)(nil),             // 16: l8api.L8MetaData
}
var file_istio_proto_depIdxs = []int32{
	0,  // 0: types.IstioVirtualServiceList.list:type_name -> types.IstioVirtualService
	16, // 1: types.IstioVirtualServiceList.metadata:type_name -> l8api.L8MetaData
	2,  // 2: types.IstioDestinationRuleList.list:type_name -> types.IstioDestinationRule
	16, // 3: types.IstioDestinationRuleList.metadata:type_name -> l8api.L8MetaData
	4,  // 4: types.IstioGatewayList.list:type_name -> types.IstioGateway
	16, // 5: types.IstioGatewayList.metadata:type_name -> l8api.L8MetaData
	6,  // 6: types.IstioServiceEntryList.list:type_name -> types.IstioServiceEntry
	16, // 7: types.IstioServiceEntryList.metadata:type_name -> l8api.L8MetaData
	8,  // 8: types.IstioPeerAuthenticationList.list:type_name -> types.IstioPeerAuthentication
	16, // 9: types.IstioPeerAuthenticationList.metadata:type_name -> l8api.L8MetaData
	10, // 10: types.IstioAuthorizationPolicyList.list:type_name -> types.IstioAuthorizationPolicy
	16, // 11: types.IstioAuthorizationPolicyList.metadata:type_name -> l8api.L8MetaData
	12, // 12: types.IstioSidecarList.list:type_name -> types.IstioSidecar
	16, // 13: types.IstioSidecarList.metadata:type_name -> l8api.L8MetaData
	14, // 14: types.IstioEnvoyFilterList.list:type_name -> types.IstioEnvoyFilter
	16, // 15: types.IstioEnvoyFilterList.metadata:type_name -> l8api.L8MetaData
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_istio_proto_init() }
func file_istio_proto_init() {
	if File_istio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_istio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioVirtualService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioVirtualServiceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioDestinationRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioDestinationRuleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioGateway); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioGatewayList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioServiceEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioServiceEntryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioPeerAuthentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioPeerAuthenticationList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioAuthorizationPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioAuthorizationPolicyList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioSidecar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioSidecarList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioEnvoyFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_istio_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IstioEnvoyFilterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_istio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_istio_proto_goTypes,
		DependencyIndexes: file_istio_proto_depIdxs,
		MessageInfos:      file_istio_proto_msgTypes,
	}.Build()
	File_istio_proto = out.File
	file_istio_proto_rawDesc = nil
	file_istio_proto_goTypes = nil
	file_istio_proto_depIdxs = nil
}
