//
// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: vcluster.proto

package types

import (
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// vCluster (SA 17)
type K8SVCluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace       string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status          string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	K8SVersion      string `protobuf:"bytes,4,opt,name=k8s_version,json=k8sVersion,proto3" json:"k8s_version,omitempty"`
	Distro          string `protobuf:"bytes,5,opt,name=distro,proto3" json:"distro,omitempty"`
	Connected       string `protobuf:"bytes,6,opt,name=connected,proto3" json:"connected,omitempty"`
	SyncedPods      int32  `protobuf:"varint,7,opt,name=synced_pods,json=syncedPods,proto3" json:"synced_pods,omitempty"`
	SyncedServices  int32  `protobuf:"varint,8,opt,name=synced_services,json=syncedServices,proto3" json:"synced_services,omitempty"`
	SyncedIngresses int32  `protobuf:"varint,9,opt,name=synced_ingresses,json=syncedIngresses,proto3" json:"synced_ingresses,omitempty"`
	Age             string `protobuf:"bytes,10,opt,name=age,proto3" json:"age,omitempty"`
	ClusterName     string `protobuf:"bytes,100,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Key             string `protobuf:"bytes,101,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *K8SVCluster) Reset() {
	*x = K8SVCluster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcluster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *K8SVCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SVCluster) ProtoMessage() {}

func (x *K8SVCluster) ProtoReflect() protoreflect.Message {
	mi := &file_vcluster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SVCluster.ProtoReflect.Descriptor instead.
func (*K8SVCluster) Descriptor() ([]byte, []int) {
	return file_vcluster_proto_rawDescGZIP(), []int{0}
}

func (x *K8SVCluster) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *K8SVCluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *K8SVCluster) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *K8SVCluster) GetK8SVersion() string {
	if x != nil {
		return x.K8SVersion
	}
	return ""
}

func (x *K8SVCluster) GetDistro() string {
	if x != nil {
		return x.Distro
	}
	return ""
}

func (x *K8SVCluster) GetConnected() string {
	if x != nil {
		return x.Connected
	}
	return ""
}

func (x *K8SVCluster) GetSyncedPods() int32 {
	if x != nil {
		return x.SyncedPods
	}
	return 0
}

func (x *K8SVCluster) GetSyncedServices() int32 {
	if x != nil {
		return x.SyncedServices
	}
	return 0
}

func (x *K8SVCluster) GetSyncedIngresses() int32 {
	if x != nil {
		return x.SyncedIngresses
	}
	return 0
}

func (x *K8SVCluster) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *K8SVCluster) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *K8SVCluster) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type K8SVClusterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*K8SVCluster    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *K8SVClusterList) Reset() {
	*x = K8SVClusterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcluster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *K8SVClusterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SVClusterList) ProtoMessage() {}

func (x *K8SVClusterList) ProtoReflect() protoreflect.Message {
	mi := &file_vcluster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SVClusterList.ProtoReflect.Descriptor instead.
func (*K8SVClusterList) Descriptor() ([]byte, []int) {
	return file_vcluster_proto_rawDescGZIP(), []int{1}
}

func (x *K8SVClusterList) GetList() []*K8SVCluster {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *K8SVClusterList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_vcluster_proto protoreflect.FileDescriptor

var file_vcluster_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xea, 0x02, 0x0a, 0x0b, 0x4b, 0x38, 0x53, 0x56, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x6b, 0x38, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6b, 0x38, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x5f, 0x70, 0x6f,
	0x64, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64,
	0x50, 0x6f, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73,
	0x79, 0x6e, 0x63, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x29, 0x0a,
	0x10, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x49,
	0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x68, 0x0a, 0x0f, 0x4b, 0x38, 0x53, 0x56, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4b, 0x38, 0x53, 0x56, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c,
	0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0x21, 0x0a, 0x0d, 0x63, 0x6f, 0x6d,
	0x2e, 0x6b, 0x38, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x42, 0x05, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x50, 0x01, 0x5a, 0x07, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vcluster_proto_rawDescOnce sync.Once
	file_vcluster_proto_rawDescData = file_vcluster_proto_rawDesc
)

func file_vcluster_proto_rawDescGZIP() []byte {
	file_vcluster_proto_rawDescOnce.Do(func() {
		file_vcluster_proto_rawDescData = protoimpl.X.CompressGZIP(file_vcluster_proto_rawDescData)
	})
	return file_vcluster_proto_rawDescData
}

var file_vcluster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vcluster_proto_goTypes = []interface{}{
	(*K8SVCluster)(nil),      // 0: types.K8SVCluster
	(*K8SVClusterList)(nil),  // 1: types.K8SVClusterList
	(*l8api.L8MetaData)(nil), // 2: l8api.L8MetaData
}
var file_vcluster_proto_depIdxs = []int32{
	0, // 0: types.K8SVClusterList.list:type_name -> types.K8SVCluster
	2, // 1: types.K8SVClusterList.metadata:type_name -> l8api.L8MetaData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vcluster_proto_init() }
func file_vcluster_proto_init() {
	if File_vcluster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vcluster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*K8SVCluster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcluster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*K8SVClusterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vcluster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vcluster_proto_goTypes,
		DependencyIndexes: file_vcluster_proto_depIdxs,
		MessageInfos:      file_vcluster_proto_msgTypes,
	}.Build()
	File_vcluster_proto = out.File
	file_vcluster_proto_rawDesc = nil
	file_vcluster_proto_goTypes = nil
	file_vcluster_proto_depIdxs = nil
}
